- name: Source asdf in bashrc
  lineinfile:
    line: "source /home/{{user_name}}/.asdf/asdf.sh"
    dest: "/home/{{user_name}}/.bash_profile"
    create: yes
    owner: "{{user_name}}"
  become_user: "{{ user_name }} -i"

- name: Add asdf plugins for Go
  command: "bash -lc 'asdf plugin-add golang https://github.com/kennyp/asdf-golang.git'"
  failed_when: false
  become_user: "{{ user_name }} -i"

- name: Install Go using asdf
  command: "bash -lc 'asdf install golang 1.12'"
  become_user: "{{ user_name }} -i"

- name: Set Go version using asdf
  command: "bash -lc 'asdf global golang 1.12'"
  become_user: "{{ user_name }} -i"

- name: Ensure directory for GOPATH exists
  file:
    path: /opt/go/
    state: directory

- name: Add GOPATH to bash profile
  lineinfile:
    line: "export GOPATH=/opt/go/"
    dest: "/root/.profile"
    create: yes
    owner: "{{user_name}}"
  become_user: "{{ user_name }} -i"

- name: Add PATH to bash profile
  lineinfile:
    line: "export PATH=$PATH:$GOPATH/bin"
    dest: "/root/.profile"
    create: yes
    owner: "{{user_name}}"
  become_user: "{{ user_name }} -i"
